---
# Ansible的被控設備清單(inventory)
# 編輯參考：
# - How to build your inventory — Ansible Documentation
#   https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
#
# Copyright 2021 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0

all:
  vars:
    ansible_user: vagrant

  # 主機定義
  hosts:
    default:
      ansible_host: 192.168.50.11
      ansible_ssh_private_key_file: .vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key

  # 主機群組定義
  children:
