---
# Ansible inventory for local development testing
#
# Reference:
# - How to build your inventory — Ansible Documentation
#   https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
#
# Copyright 2021 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0+

all:
  vars:
    ansible_user: vagrant

  hosts:
    default:
      ansible_host: 192.168.50.11
      ansible_ssh_private_key_file: >-
        .vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key

  children:
