# Markdownlint(Node.js variant) configuration file
# https://github.com/igorshubovych/markdownlint-cli#configuration
#
# This file is based on The Common Markdownlint(Node.js variant)
# Configuration Templates project
# https://github.com/the-common/markdownlint-nodejs-config-templates
#
# Copyright 2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0

# Inherit Markdownlint rules
default: True

# Only allow consistent un-ordered list bullet style(allow alternations
# in sub-levels)
ul-style:
  style: sublist

# Only allow 4 spaces as indentation of lists
ul-indent:
  indent: 4

# Only allow 2 spaces as linebreak sequence
no-trailing-spaces:
  br_spaces: 2

# Disable line length limitation(not suitable with CJK context)
line-length: False

# Allow missing padding blank line between the heading markup and the context
blanks-around-headings: False

# Allow duplicated non-sibling heading text
no-duplicate-heading:
  siblings_only: True

# Allow missing padding blank line between a list and its context
blanks-around-lists: False

# Allow using raw HTML markups as workarounds of deficiencies of Markdown
no-inline-html: False

# Allow using YAML front matter, while not require the definition of the
# `title` property
first-line-h1:
  front_matter_title: '.*'
