# Requirements of this Ansible project
#
# This file defines required roles and/or collections of this Ansible
# project that can be installed using the following command:
#
#     ansible-galaxy install -r requirements.yml
#
# References:
#
# * Installing multiple roles from a file — Galaxy User Guide — Ansible
#   Community Documentation
#   https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-multiple-roles-from-a-file
# * Installing roles and collections from the same requirements.yml file
#   — Galaxy User Guide — Ansible Community Documentation
#   https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-roles-and-collections-from-the-same-requirements-yml-file
#
# Copyright 2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0
roles:
  # For switching to local software archive mirror
  - name: chusiang.switch-apt-mirror
    version: 1.0.7

  # For installing Docker-related packages
  - name: geerlingguy.docker
    version: 7.3.0

  # For installing Oracle VirtualBox
  - name: brlin.virtualbox
    src: https://gitlab.com/brlin/ansible-role-virtualbox.git
    scm: git
    version: temp/patches-applied

collections:
  # Dependency of the community.general.yaml callback plugin
  # Dependency of the community.general.snap module
  - name: community.general
    version: 8.6.1

  # For installing Vagrant
  - name: enmanuelmoreira.hashicorp
    version: 1.4.1
