# Cleanup customizations from old versions of the playbook
#
# Copyright 2023 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0+

- name: Cleanup old udev configuration files
  become: true
  notify:
    - Apply udev rule changes
  loop_control:
    loop_var: udev_rule_filename
  loop:
    - 85-nm-unmanaged-veth.rules
  ansible.builtin.file:
    path: /etc/udev/rules.d/{{ udev_rule_filename }}
    state: absent
