# Configure user bashrc according to my preferences
# Copyright 2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0

- name: Configure dquilt command for Debian packaging.
  ansible.builtin.copy:
    src: dot-bashrc.d/setup-dquilt-for-debian-packaging.source.sh
    dest: '{{ _bashrc_d_dir }}/10-setup-dquilt-for-debian-packaging.source.sh'
    mode: '0644'

- name: Configure Powerline shell.
  ansible.builtin.copy:
    src: dot-bashrc.d/setup-powerline-shell.source.sh
    dest: '{{ _bashrc_d_dir }}/10-setup-powerline-shell.source.sh'
    mode: '0644'

- name: Configure RVM.
  ansible.builtin.copy:
    src: dot-bashrc.d/setup-rvm.source.sh
    dest: '{{ _bashrc_d_dir }}/10-setup-rvm.source.sh'
    mode: '0644'
