# Task list for deploying Hashicorp Vagrant to the managed nodes
#
# Copyright 2024 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0
- name: Delegate the task to the enmanuelmoreira.hashicorp.vagrant role to do the installation.
  become: true
  vars:
    vagrant_experimental: "{{ vagrant_experimental_override }}"
    vagrant_force_color: "{{ vagrant_force_color_override }}"
    vagrant_no_parallel: "{{ vagrant_no_parallel_override }}"
  ansible.builtin.import_role:
    name: enmanuelmoreira.hashicorp.vagrant
    public: false
