# Task list for deploying .bashrc.d to the managed nodes
#
# Copyright 2024 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0+
- name: Fetch the releases information of .bashrc.d from GitHub.
  register: _bashrc_d_github_releases
  failed_when: >-
    _bashrc_d_github_releases is failed
    or _bashrc_d_github_releases.status != 200
    or _bashrc_d_github_releases.content | length == 0
  ansible.builtin.uri:
    url: https://api.github.com/repos/brlin-tw/dot-bashrc.d/releases
    return_content: true
    headers:
      Accept: application/vnd.github+json
      X-GitHub-Api-Version: 2022-11-28

- name: Determine the latest stable release of .bashrc.d.
  ansible.builtin.set_fact:
    _bashrc_d_latest_release: >-
      {{
        _bashrc_d_github_releases.json
          | community.general.json_query('[?prerelease == `false`] | [0]')
      }}

- name: Determine the release archive asset of the latest stable release.
  ansible.builtin.set_fact:
    _bashrc_d_release_archive_asset: >-
      {{
        _bashrc_d_latest_release
          | community.general.json_query('assets[?ends_with(name, `"tar.gz"`)] | [0]')
      }}

- name: Determine the download URL of the .bashrc.d release archive.
  ansible.builtin.set_fact:
    _bashrc_d_release_archive_url: >-
      {{
        _bashrc_d_release_archive_asset.browser_download_url
      }}
    _bashrc_d_release_archive_name: >-
      {{
        _bashrc_d_release_archive_asset.name
      }}

- name: Ensure the cache directory exists.
  ansible.builtin.file:
    path: '{{ cache_dir }}'
    state: directory
    mode: '0755'

- name: Determine the path of the cached .bashrc.d release archive.
  ansible.builtin.set_fact:
    _bashrc_d_release_archive_cached: '{{ cache_dir }}/{{ _bashrc_d_release_archive_name }}'

- name: Check whether the cached .bashrc.d release archive exists
  register: cached_release_archive_existence_raw
  ansible.builtin.stat:
    path: '{{ _bashrc_d_release_archive_cached }}'

- name: Download release archive of .bashrc.d.
  when: not cached_release_archive_existence_raw.stat.exists
  ansible.builtin.get_url:
    url: '{{ _bashrc_d_release_archive_url }}'
    dest: '{{ _bashrc_d_release_archive_cached }}'
    mode: '0644'

- name: Create a temporary directory for extracting the .bashrc.d release archive.
  register: _bashrc_d_tempdir
  notify: Clear the temporary directory for extracting the .bashrc.d release archive.
  ansible.builtin.tempfile:
    state: directory

- name: Extract the .bashrc.d release archive.
  ansible.builtin.unarchive:
    src: '{{ _bashrc_d_release_archive_cached }}'
    dest: '{{ _bashrc_d_tempdir.path }}'
    extra_opts:
      # Remove the leading product release folder for logic consistency
      - --strip-components=1

- name: Run the .bashrc.d installation program.
  # We currently cannot determine whether the product installation program have changed anything, always assuming managed nodes have changed.
  changed_when: true
  ansible.builtin.command: '{{ _bashrc_d_tempdir.path }}/install.sh'
