# Task list for deploying the GNOME desktop environment
#
# Copyright 2024 林博仁(Buo-ren, Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0

- name: Ensure that the GNOME desktop environment is installed, which is one of my fallback operating environments.
  when: ansible_distribution != 'Ubuntu'
  become: true
  ansible.builtin.package:
    name: gnome-session

- name: Ensure that the Ubuntu desktop environment(based on GNOME 3) is installed, which is one of my fallback operating environments.
  when: ansible_distribution == 'Ubuntu'
  become: true
  ansible.builtin.package:
    name: ubuntu-session
