# Task list for installing and configuring my preferred software
#
# Copyright 2024 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0

- name: Ensure that the software repository local cache is fresh
  ansible.builtin.import_tasks: ensure-software-repository-local-cache-is-fresh.yml

- name: >-
    Setup the OpenSSH service for remote administration convenience.
  become: true
  ansible.builtin.package:
    name: openssh-server

- name: >-
    Setup Fail2ban to prevent bruteforce attack of the SSH service.
  become: true
  ansible.builtin.package:
    name: fail2ban

- name: >-
    Allow workstation to be broadcasted via Multicast for access
    convenience.
  become: true
  notify:
    - Reload Avahi daemon config
  ansible.builtin.replace:
    path: /etc/avahi/avahi-daemon.conf
    regexp: '^publish-workstation=.*$'
    replace: publish-workstation=yes

- name: >-
    Ensure that the GHex hex editor is installed, which is useful
    in examining binary files.
  become: true
  ansible.builtin.package:
    name:
      - ghex

- name: >-
    Ensure that the Git version control system is installed, which
    is used to manage personal and third-party projects.
  become: true
  ansible.builtin.package:
    name:
      - git

- name: >-
    Ensure that the Git Large File System(LFS) software is
    installed, which allows managing huge binary objects in a Git
    repository.
  become: true
  ansible.builtin.package:
    name:
      - git-lfs

- name: >-
    Ensure that the gridsite-clients package is installed, which
    provides the `urlencode` command for encoding and decoding
    percent-encoded URLs.
  become: true
  ansible.builtin.package:
    name:
      - gridsite-clients

- name: >-
    Ensure that the htop process viewer utility is installed,
    which is used to examine and manipulate the running processes.
  become: true
  ansible.builtin.package:
    name:
      - htop

- name: >-
    Ensure that the iftop utility is installed, which is used to
    monitor the data transfer of the network connections.
  become: true
  ansible.builtin.package:
    name:
      - iftop

- name: >-
    Ensure that the iotop utility is installed, which is used to
    monitor the data transfer of the storage devices.
  become: true
  ansible.builtin.package:
    name:
      - iotop

- name: >-
    Ensure that the Kate Editor is installed, which is a powerful
    plaintext file editor with syntax highlighting and other
    powerful features.
  become: true
  ansible.builtin.package:
    name:
      - kate

- name: >-
    Ensure that the KeePassXC application is installed, which is
    used to manage secret information in the KeePass Password
    Safes.
  become: true
  ansible.builtin.package:
    name:
      - keepassxc

- name: >-
    Ensure that the lm-sensors package is installed, which allows
    one to read the system's hardware sensor data.
  become: true
  ansible.builtin.package:
    name:
      - lm-sensors

- name: >-
    Ensure that the pipx utility is installed, which is used to
    cleanly manage Python applications using separate virtual
    environments.
  become: true
  ansible.builtin.package:
    name:
      - pipx

- name: >-
    Ensure that the tmux terminal multiplexer is installed,
    which allows multiple terminals be created on a single one.
  become: true
  ansible.builtin.package:
    name:
      - tmux

- name: >-
    Ensure that the vcsh config manager is installed, which
    allows using the Git version control system to manage my
    configuration files.
  become: true
  ansible.builtin.package:
    name:
      - vcsh

- name: >-
    Ensure that the vim plaintext editor is installed, which
    allows high efficiency text editing.
  become: true
  ansible.builtin.package:
    name:
      - vim

- name: >-
    Ensure that the WireGuard VPN software is installed, which
    is used to connect some of the VPN services.
  become: true
  ansible.builtin.package:
    name:
      - wireguard

- name: Install codecs for multimedia playback.
  become: true
  ansible.builtin.package:
    name:
      - ubuntu-restricted-extras

- name: >-
    Ensure that the KDE desktop environment is installed, which
    provides feature-rich desktop experience.
  become: true
  ansible.builtin.package:
    name:
      - kde-standard
      # Wayland session
      - plasma-workspace-wayland

- name: >-
    Ensure that the XFCE desktop environment is installed, which
    provides light-weight desktop experience.
  become: true
  ansible.builtin.package:
    name:
      - xfce4

- name: >-
    Ensure that the curl HTTP(S)/FTP/etc... client is installed, which
    is used for service testing.
  become: true
  ansible.builtin.package:
    name:
      - curl

- name: >-
    Setup the LXD container engine, which is used for building
    snaps and for testing
  rescue:
    - name: Interrupt the play if any of the block tasks failed.
      ansible.builtin.fail:
        msg: 'Error: Unable to setup the LXD container engine.'
  block:
    - name: >-
        Ensure that the LXD container engine is installed, which is used
        for building snaps and for testing.
      become: true
      community.general.snap:
        name: lxd

    - name: >-
        Add the running user to the LXD user group to allow easy access
        to the container engine.
      become: true
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        groups:
          - lxd
        append: true

    - name: Making LXD bridge interfaces not managed by NetworkManager.
      become: true
      notify:
        - Apply udev rule changes
        - Reload NetworkManager configuration
      ansible.builtin.copy:
        src: udev.rules.d/dont-manage-lxd-managed-bridges.rules
        dest: /etc/udev/rules.d/85-nm-unmanaged-lxd.rules
        owner: root
        group: root
        mode: '0644'

- name: >-
    Ensure that the Snapcraft packaging tool is installed, which is
    used for building snaps.
  become: true
  community.general.snap:
    name: snapcraft
    classic: true

- name: >-
    Ensure that the Asciiquarium utility is installed, which presents a
    nice aquarium view in the text terminal.
  become: true
  community.general.snap:
    name: asciiquarium

- name: >-
    Ensure that the Steam gaming platform is installed, which is used
    to manage some of the games of mine.
  when: >-
    ansible_architecture == "i386"
      or ansible_architecture == "x86_64"
  rescue:
    - name: Interrupt the play if any of the block tasks failed.
      ansible.builtin.fail:
        msg: 'Error: Unable to install the Steam gaming platform.'
  block:
    - name: >-
        Query the foreign architectures enabled in the APT package
        management system.
      register: dpkg_foreign_arches_raw
      changed_when: false
      ansible.builtin.command: dpkg --print-foreign-architectures

    - name: >-
        Ensure that the i386 architecture of the APT package management
        system is enabled to install Steam's runtime dependencies.
      when: >-
        ansible_architecture == "x86_64"
          and "i386" not in dpkg_foreign_arches_raw.stdout_lines
      become: true
      register: dpkg_add_architecture_result
      changed_when: dpkg_add_architecture_result.rc == 0
      ansible.builtin.command: dpkg --add-architecture i386

    - name: >-
        Ensure that the Steam gaming platform is installed, which is used
        to manage some of my games.
      become: true
      ansible.builtin.package:
        name: steam-installer

- name: >-
    Ensure that the Git Cola application is installed, which is used to
    manage Git repositories.
  become: true
  ansible.builtin.package:
    name: git-cola

- name: >-
    Ensure that the html-query(hq) utility is installed, which is
    used to parse the HTML document in some scripts.
  rescue:
    - name: Interrupt the play if any of the block tasks failed.
      ansible.builtin.fail:
        msg: 'Error: Unable to deploy the html-query(hq) utility.'
  block:
    - name: >-
        Ensure that the html-query(hq) utility is installed,
        which is used to parse the HTML document in some scripts.
      become: true
      community.general.snap:
        name: orf-hq

    - name: >-
        Setup convenient command aliases for the html-query
        utility.
      become: true
      community.general.snap_alias:
        name: orf-hq
        alias: hq

- name: >-
    Ensure that the KolourPaint application is installed, which
    is used for annotate the screenshots.
  become: true
  ansible.builtin.package:
    name: kolourpaint

- name: >-
    Ensure that the bindfs utility is installed, which is used to
    workaround limitations regarding paths containing spaces of
    build utilities like Make.
  become: true
  ansible.builtin.package:
    name: bindfs

- name: >-
    Ensure that the Epson Imagescan V2 application is installed.
  rescue:
    - name: Interrupt the play if any of the block tasks failed.
      ansible.builtin.fail:
        msg: >-
          Error: Unable to deploy the Epson Imagescan V2 application.
  block:
    - name: >-
        Ensure that the Epson Imagescan V2 application is installed,
        which is used to support scanning document/photos from an
        Epson scanner on GNU+Linux
      become: true
      community.general.snap:
        name: iscan

    - name: >-
        Ensure that the iscan snap is connected to the raw-usb snapd
        confinement interface, so that it can communicate with the
        USB scanners.
      become: true
      register: iscan_interface_connect_result_raw
      changed_when: >-
        iscan_interface_connect_result_raw.rc == 0
          and not iscan_interface_connect_result_raw.stdout_lines
      ansible.builtin.command: snap connect iscan:raw-usb

- name: >-
    Ensure that the QtQR application is installed, which is used to
    scan QR codes without resort to using the mobile devices.
  become: true
  ansible.builtin.package:
    name: qtqr

- name: Enable the Flatpak package support.
  rescue:
    - name: Interrupt the play if any of the block tasks failed.
      ansible.builtin.fail:
        msg: >-
          Error: Unable to enable the Flatpak package support.
  block:
    - name: >-
        Enable the Flatpak stable versions PPA software source.
      # Refer PPA support status at:
      # https://launchpad.net/~flatpak/+archive/ubuntu/stable
      when: >-
        ansible_distribution == 'Ubuntu'
          and (
            ansible_distribution_version == '22.04'
            or ansible_distribution_version == '20.04'
          )
      ansible.builtin.apt_repository:
        repo: ppa:flatpak/stable

    - name: Ensure that the Flatpak runtime is installed.
      become: true
      ansible.builtin.package:
        name: flatpak

    - name: >-
        Ensure that the Flatpak plugin of the GNOME Software
        application is installed.
      become: true
      ansible.builtin.package:
        name: gnome-software-plugin-flatpak

    - name: >-
        Ensure that the Flatpak backend of the KDE Discover
        application is installed.
      become: true
      ansible.builtin.package:
        name: plasma-discover-backend-flatpak

    - name: Ensure that the Flathub repository is enabled.
      become: true
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Ensure that the OBS Studio application is installed.
  become: true
  community.general.flatpak:
    name: com.obsproject.Studio
    remote: flathub

- name: >-
    Ensure that the Image Density Fixer application is installed, for improving
    the quality of OCR-ing camera-captured documents.
  become: true
  community.general.snap:
    name: image-density-fixer

- name: >-
    Ensure that the sshpass utility is installed, which is required for Ansible
    to connect to SSH servers.
  become: true
  ansible.builtin.package:
    name: sshpass

- name: >-
    Ensure that the tldr utility is installed, which is used to viewing tldr
    pages.
  rescue:
    - name: Interrupt the play if any of the block tasks failed.
      ansible.builtin.fail:
        msg: 'Error: Unable to install the tldr utility'
  block:
    - name: >-
        Ensure that the tldr utility is installed, which is used to viewing tldr
        pages.
      become: true
      ansible.builtin.package:
        name: tealdeer

    - name: Update the local cache of the tldr pages.
      become: false
      register: tldr_update_result_raw
      changed_when: tldr_update_result_raw.rc == 0
      ansible.builtin.command: tldr --update

- name: >-
    Ensure that the OCRmyPDF application is installed, which is used for OCR-ing
    scanned documents.
  become: true
  community.general.snap:
    name: ocrmypdf
    channel: edge
