# Default task list
#
# Copyright 2021 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0

- name: Update local software sources cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Apply system updates to avoid known issues
  become: true
  ansible.builtin.package:
    # We specifically intend to upgrade all packages here
    # noqa package-latest
    name: '*'
    state: latest

- name: Install OpenSSH server for administration convenience
  become: true
  ansible.builtin.package:
    name: openssh-server

- name: Install Fail2ban to prevent bruteforce attack of SSH service
  become: true
  ansible.builtin.package:
    name: fail2ban

- name: Allow workstation to be broadcasted via Multicast for discover convenience
  become: true
  notify:
    - Reload Avahi daemon config
  ansible.builtin.replace:
    path: /etc/avahi/avahi-daemon.conf
    regexp: '^publish-workstation=.*$'
    replace: publish-workstation=yes

- name: Install common utilities
  become: true
  ansible.builtin.package:
    name:
      - ghex
      - git
      - git-lfs
      # For the `urlencode` command
      - gridsite-clients
      - htop
      - iftop
      - iotop
      - kate
      - keepassxc
      - lm-sensors
      - pipx
      - tmux
      - vcsh
      - vim
      - wireguard

- name: Install codecs for multimedia playback
  become: true
  ansible.builtin.package:
    name:
      - ubuntu-restricted-extras

- name: Making Docker bridge interfaces not managed by NetworkManager
  become: true
  notify:
    - Apply udev rule changes
    - Reload NetworkManager configuration
  ansible.builtin.copy:
    src: dont-manage-docker-managed-bridges.rules
    dest: /etc/udev/rules.d/85-nm-unmanaged-docker.rules
    owner: root
    group: root
    mode: 0644

- name: Making LXD bridge interfaces not managed by NetworkManager
  become: true
  notify:
    - Apply udev rule changes
    - Reload NetworkManager configuration
  ansible.builtin.copy:
    src: dont-manage-lxd-managed-bridges.rules
    dest: /etc/udev/rules.d/85-nm-unmanaged-lxd.rules
    owner: root
    group: root
    mode: 0644

- name: Making libvirt bridge interfaces not managed by NetworkManager
  become: true
  notify:
    - Apply udev rule changes
    - Reload NetworkManager configuration
  ansible.builtin.copy:
    src: dont-manage-libvirt-managed-bridges.rules
    dest: /etc/udev/rules.d/85-nm-unmanaged-libvirt.rules
    owner: root
    group: root
    mode: 0644

- name: Making Multipass bridge interfaces not managed by NetworkManager
  become: true
  notify:
    - Apply udev rule changes
    - Reload NetworkManager configuration
  ansible.builtin.copy:
    src: dont-manage-multipass-qemu-bridges.rules
    dest: /etc/udev/rules.d/85-nm-unmanaged-multipass.rules
    owner: root
    group: root
    mode: 0644

- name: Making virtual ethernet device(veth) interfaces not managed by NetworkManager
  become: true
  notify:
    - Reload NetworkManager configuration
  ansible.builtin.copy:
    src: NetworkManager.conf.d/90-unmanage-virtual-ethernet-network-interfaces.conf
    dest: /etc/NetworkManager/conf.d/90-unmanage-virtual-ethernet-network-interfaces.conf
    owner: root
    group: root
    mode: 0644

- name: Install preferred desktop environments
  become: true
  ansible.builtin.package:
    name:
      - kde-standard
      - xfce4

- name: Cleanup customizations from old versions of the playbook
  ansible.builtin.import_tasks: cleanup.yml

- name: Reboot
  when: ansible_connection != "local"
  become: true
  ansible.builtin.reboot:

- name: Report final result
  ansible.builtin.debug:
    msg: Customization finished, if the playbook is run on the localhost please reboot the system to apply modifications.
