# Default task list
#
# Copyright 2021 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0

- name: Use Taiwan local Ubuntu mirror to reduce package download time.
  vars:
    ubuntu_apt_mirror: tw.archive.ubuntu.com
  ansible.builtin.include_role:
    name: chusiang.switch-apt-mirror
    apply:
      become: true

- name: Ensure that the APT local software sources cache is fresh
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Apply system updates to avoid known issues
  become: true
  ansible.builtin.package:
    # We specifically intend to upgrade all packages here
    # noqa package-latest
    name: '*'
    state: latest

- name: Setup the OpenSSH service for remote administration convenience
  become: true
  ansible.builtin.package:
    name: openssh-server

- name: Setup Fail2ban to prevent bruteforce attack of the SSH service
  become: true
  ansible.builtin.package:
    name: fail2ban

- name: Allow workstation to be broadcasted via Multicast for access convenience
  become: true
  notify:
    - Reload Avahi daemon config
  ansible.builtin.replace:
    path: /etc/avahi/avahi-daemon.conf
    regexp: '^publish-workstation=.*$'
    replace: publish-workstation=yes

- name: >-
    Ensure that the GHex hex editor is installed, which is useful in examining binary files.
  become: true
  ansible.builtin.package:
    name:
      - ghex

- name: >-
    Ensure that the Git version control system is installed, which
    is used to manage personal and third-party projects.
  become: true
  ansible.builtin.package:
    name:
      - git

- name: >-
    Ensure that the Git Large File System(LFS) software is
    installed, which allows managing huge binary objects in a Git
    repository.
  become: true
  ansible.builtin.package:
    name:
      - git-lfs

- name: >-
    Ensure that the gridsite-clients package is installed, which
    provides the `urlencode` command for encoding and decoding
    percent-encoded URLs.
  become: true
  ansible.builtin.package:
    name:
      - gridsite-clients

- name: >-
    Ensure that the htop process viewer utility is installed,
    which is used to examine and manipulate the running processes.
  become: true
  ansible.builtin.package:
    name:
      - htop

- name: >-
    Ensure that the iftop utility is installed, which is used to
    monitor the data transfer of the network connections.
  become: true
  ansible.builtin.package:
    name:
      - iftop

- name: >-
    Ensure that the iotop utility is installed, which is used to
    monitor the data transfer of the storage devices.
  become: true
  ansible.builtin.package:
    name:
      - iotop

- name: >-
    Ensure that the Kate Editor is installed, which is a powerful
    plaintext file editor with syntax highlighting and other
    powerful features.
  become: true
  ansible.builtin.package:
    name:
      - kate

- name: >-
    Ensure that the KeePassXC application is installed, which is
    used to manage secret information in the KeePass Password
    Safes.
  become: true
  ansible.builtin.package:
    name:
      - keepassxc

- name: >-
    Ensure that the lm-sensors package is installed, which allows
    one to read the system's hardware sensor data.
  become: true
  ansible.builtin.package:
    name:
      - lm-sensors

- name: >-
    Ensure that the pipx utility is installed, which is used to
    cleanly manage Python applications using separate virtual
    environments.
  become: true
  ansible.builtin.package:
    name:
      - pipx

- name: >-
    Ensure that the tmux terminal multiplexer is installed, which allows multiple terminals be created on a single one.
  become: true
  ansible.builtin.package:
    name:
      - tmux

- name: >-
    Ensure that the vcsh config manager is installed, which allows using the Git version control system to manage my configuration files.
  become: true
  ansible.builtin.package:
    name:
      - vcsh

- name: >-
    Ensure that the vim plaintext editor is installed, which
    allows high efficiency text editing.
  become: true
  ansible.builtin.package:
    name:
      - vim

- name: >-
    Ensure that the WireGuard VPN software is installed, which
    is used to connect some of the VPN services.
  become: true
  ansible.builtin.package:
    name:
      - wireguard

- name: Install codecs for multimedia playback
  become: true
  ansible.builtin.package:
    name:
      - ubuntu-restricted-extras

- name: Making Docker bridge interfaces not managed by NetworkManager
  become: true
  notify:
    - Apply udev rule changes
    - Reload NetworkManager configuration
  ansible.builtin.copy:
    src: udev.rules.d/dont-manage-docker-managed-bridges.rules
    dest: /etc/udev/rules.d/85-nm-unmanaged-docker.rules
    owner: root
    group: root
    mode: 0644

- name: Making LXD bridge interfaces not managed by NetworkManager
  become: true
  notify:
    - Apply udev rule changes
    - Reload NetworkManager configuration
  ansible.builtin.copy:
    src: udev.rules.d/dont-manage-lxd-managed-bridges.rules
    dest: /etc/udev/rules.d/85-nm-unmanaged-lxd.rules
    owner: root
    group: root
    mode: 0644

- name: Making libvirt bridge interfaces not managed by NetworkManager
  become: true
  notify:
    - Apply udev rule changes
    - Reload NetworkManager configuration
  ansible.builtin.copy:
    src: udev.rules.d/dont-manage-libvirt-managed-bridges.rules
    dest: /etc/udev/rules.d/85-nm-unmanaged-libvirt.rules
    owner: root
    group: root
    mode: 0644

- name: Making Multipass bridge interfaces not managed by NetworkManager
  become: true
  notify:
    - Apply udev rule changes
    - Reload NetworkManager configuration
  ansible.builtin.copy:
    src: udev.rules.d/dont-manage-multipass-qemu-bridges.rules
    dest: /etc/udev/rules.d/85-nm-unmanaged-multipass.rules
    owner: root
    group: root
    mode: 0644

- name: Making virtual ethernet device(veth) interfaces not managed by NetworkManager
  become: true
  notify:
    - Reload NetworkManager configuration
  ansible.builtin.copy:
    src: NetworkManager.conf.d/90-unmanage-virtual-ethernet-network-interfaces.conf
    dest: /etc/NetworkManager/conf.d/90-unmanage-virtual-ethernet-network-interfaces.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure that the KDE desktop environment is installed, which provides feature-rich desktop experience.
  become: true
  ansible.builtin.package:
    name:
      - kde-standard

- name: Ensure that the XFCE desktop environment is installed, which provides light-weight desktop experience.
  become: true
  ansible.builtin.package:
    name:
      - xfce4

- name: Cleanup customizations from old versions of the playbook
  ansible.builtin.import_tasks: cleanup.yml

- name: Reboot
  when: ansible_connection != "local"
  become: true
  ansible.builtin.reboot:

- name: Report final result
  ansible.builtin.debug:
    msg: Customization finished, if the playbook is run on the localhost please reboot the system to apply modifications.
