# Default task list
#
# Copyright 2025 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0

- name: >-
    Use Taiwan local Ubuntu mirror to reduce package download time.
  # NOTE: Ubuntu >=24.04 uses the DEP822 software source format, which
  # isn't compatible with the chusiang.switch-apt-mirror role at the
  # moment
  when: >-
    ansible_distribution_file_variety == "Debian"
      and (
        ansible_distribution == "Ubuntu"
          and ansible_distribution_version < "24.04"
      )
  vars:
    ubuntu_apt_mirror: tw.archive.ubuntu.com
  ansible.builtin.include_role:
    name: chusiang.switch-apt-mirror
    apply:
      become: true

- name: Ensure that the software repository local cache is fresh
  ansible.builtin.import_tasks: ensure-software-repository-local-cache-is-fresh.yml

- name: Apply system updates to avoid known issues.
  when: not brlinos_skip_upgrade
  become: true
  ansible.builtin.package:
    # We specifically intend to upgrade all packages here
    # noqa package-latest
    name: '*'
    state: latest

- name: Deploy preferred software.
  ansible.builtin.import_tasks: deploy-preferred-software.yml

- name: Check whether the Plastik window decoration in KDE desktop environment is configured
  become: false
  changed_when: false
  register: kde_window_decoration_theme_raw
  ansible.builtin.command:
    argv:
      - kreadconfig5
      - --file
      - kwinrc
      - --group
      - org.kde.kdecoration2
      - --key
      - theme

- name: Use Plastik window decoration in KDE desktop environment to provide a Windows-like user interface.
  when: kde_window_decoration_theme_raw.stdout != 'kwin4_decoration_qml_plastik'
  become: false
  register: plastik_configuration_result_raw
  changed_when: plastik_configuration_result_raw.rc == 0
  loop:
    - key: library
      value: org.kde.kwin.aurorae
    - key: theme
      value: kwin4_decoration_qml_plastik
  loop_control:
    loop_var: config
  ansible.builtin.command:
    argv:
      - kwriteconfig5
      - --file
      - kwinrc
      - --group
      - org.kde.kdecoration2
      - --key
      - '{{ config.key }}'
      - '{{ config.value }}'

- name: Making Docker bridge interfaces not managed by NetworkManager.
  become: true
  notify:
    - Apply udev rule changes
    - Reload NetworkManager configuration
  ansible.builtin.copy:
    src: udev.rules.d/dont-manage-docker-managed-bridges.rules
    dest: /etc/udev/rules.d/85-nm-unmanaged-docker.rules
    owner: root
    group: root
    mode: '0644'

- name: Making libvirt bridge interfaces not managed by NetworkManager.
  become: true
  notify:
    - Apply udev rule changes
    - Reload NetworkManager configuration
  ansible.builtin.copy:
    src: udev.rules.d/dont-manage-libvirt-managed-bridges.rules
    dest: /etc/udev/rules.d/85-nm-unmanaged-libvirt.rules
    owner: root
    group: root
    mode: '0644'

- name: Making Multipass bridge interfaces not managed by NetworkManager.
  become: true
  notify:
    - Apply udev rule changes
    - Reload NetworkManager configuration
  ansible.builtin.copy:
    src: udev.rules.d/dont-manage-multipass-qemu-bridges.rules
    dest: /etc/udev/rules.d/85-nm-unmanaged-multipass.rules
    owner: root
    group: root
    mode: '0644'

- name: >-
    Making virtual ethernet device(veth) interfaces not managed by
    NetworkManager
  become: true
  notify:
    - Reload NetworkManager configuration
  ansible.builtin.copy:
    src: NetworkManager.conf.d/90-unmanage-virtual-ethernet-network-interfaces.conf
    dest: /etc/NetworkManager/conf.d/90-unmanage-virtual-ethernet-network-interfaces.conf
    owner: root
    group: root
    mode: '0644'

- name: Import vcsh-managed configurations.
  rescue:
    - name: Interrupt play if any of the block sub-tasks failed.
      ansible.builtin.fail:
        msg: 'Error: Unable to import vcsh-managed configurations.'
  block:
    - name: Ensure the vcsh hook directories are created.
      loop:
        - ~/.config/vcsh/hooks-available
        - ~/.config/vcsh/hooks-enabled
      loop_control:
        loop_var: dir
      ansible.builtin.file:
        path: '{{ dir }}'
        state: directory
        mode: '0755'

    - name: >-
        Install vcsh pre-merge hook to avoid import failure due to
        pre-existing config files.
      ansible.builtin.copy:
        src: vcsh-hooks/pre-merge-10-unclobber.sh
        dest: ~/.config/vcsh/hooks-available/pre-merge-10-unclobber.sh
        mode: '0755'

    - name: Ensure the unclobber pre-merge hook is enabled
      ansible.builtin.file:
        path: ~/.config/vcsh/hooks-enabled/pre-merge-10-unclobber.sh
        src: ../hooks-available/pre-merge-10-unclobber.sh
        state: link

    - name: >-
        Satisfy the runtime dependency of the vcsh repository query
        utility.
      become: true
      ansible.builtin.package:
        name:
          - curl
          - jq

    - name: >-
        Query all vcsh-managed configuration repositories by
        Buo-ren, Lin.
      ansible.builtin.set_fact:
        vcsh_repo_names_raw: >-
          {{
            lookup(
              "ansible.builtin.lines",
              "{{ role_path | quote }}/controller-utils/query-brlin-vcsh-repositories.sh",
              wantlist=True
            )
          }}

    - name: Import vcsh-managed configurations.
      register: import_vcsh
      changed_when: import_vcsh.rc == 0
      # 10: Repo already exists
      failed_when: >-
        import_vcsh.rc != 0
        and import_vcsh.rc != 10
      loop: '{{ vcsh_repo_names_raw }}'
      loop_control:
        loop_var: vcsh_repo_name
      ansible.builtin.command:
        argv:
          - vcsh
          - clone
          - https://github.com/brlin-tw/{{ vcsh_repo_name }}.git
          - '{{ vcsh_repo_name | replace("vcsh-", "") }}'

- name: Configure user profile settings.
  ansible.builtin.include_tasks: configure-user-profile.yml

- name: Configure bash runcommands settings.
  ansible.builtin.include_tasks: configure-user-bashrc.yml

- name: Cleanup customizations from old versions of the playbook.
  ansible.builtin.import_tasks: cleanup.yml

- name: Reboot.
  when: ansible_connection != "local"
  become: true
  ansible.builtin.reboot:

- name: Report final result.
  ansible.builtin.debug:
    msg: Customization finished, if the playbook is run on the localhost please reboot the system to apply modifications.
