# Default task list
#
# Copyright 2021 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0

- name: Update local software sources cache
  become: True
  apt:
    update_cache: yes

- name: Apply system updates to avoid known issues
  become: True
  package:
    name: '*'
    state: latest

- name: Install OpenSSH server for administration convenience
  become: True
  package:
    name: openssh-server

- name: Install Fail2ban to prevent bruteforce attack of SSH service
  become: True
  package:
    name: fail2ban

- name: Allow workstation to be broadcasted via Multicast for discover convenience
  rescue:
    - name: Bailout when any task failed
      fail:
        msg: Error occurred during customizing Avahi daemon settings
  block:
    - name: 'Allow workstation to be broadcasted via Multicast for discover convenience: Patch Avahi daemon configuration'
      become: True
      register: avahi_patched
      replace:
        path: /etc/avahi/avahi-daemon.conf
        regexp: '^publish-workstation=.*$'
        replace: publish-workstation=yes

    - name: 'Allow workstation to be broadcasted via Multicast for discover convenience: Reload Avahi daemon config'
      become: True
      when: avahi_patched.changed
      service:
        name: avahi-daemon.service
        # reload doesn't work
        state: restarted

- name: Install common utilities
  become: True
  package:
    name:
      - ghex
      - git
      - git-lfs
      # For the `urlencode` command
      - gridsite-clients
      - htop
      - iftop
      - iotop
      - kate
      - keepassxc
      - lm-sensors
      - pipx
      - tmux
      - vcsh
      - vim
      - wireguard

- name: Install codecs for multimedia playback
  become: True
  package:
    name:
      - ubuntu-restricted-extras
