---
# Ansible的被控設備清單(inventory)
# 編輯參考：
# - How to build your inventory — Ansible Documentation
#   https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
all:
  # 主機定義
  hosts:
    localhost:
      ansible_connection: local
      ansible_become_password: sudopass
