# Default handlers list
#
# Copyright 2025 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0+
- name: Apply udev rule changes
  become: true
  changed_when: true
  ansible.builtin.command: udevadm control --reload

- name: Reload NetworkManager configuration
  become: true
  ansible.builtin.service:
    name: NetworkManager.service
    state: reloaded

- name: Reload Avahi daemon config
  become: true
  ansible.builtin.service:
    name: avahi-daemon.service
    # reload doesn't work
    state: restarted

- name: Clear the temporary directory for extracting the .profile.d release archive.
  when: _profile_d_tempdir.path is defined
  ansible.builtin.file:
    path: '{{ _profile_d_tempdir.path }}'
    state: absent

- name: Clear the temporary directory for extracting the .bashrc.d release archive.
  when: _bashrc_d_tempdir.path is defined
  ansible.builtin.file:
    path: '{{ _bashrc_d_tempdir.path }}'
    state: absent

- name: Restart systemd-sysctl service
  become: true
  ansible.builtin.service:
    name: systemd-sysctl.service
    state: restarted
