# Default handlers list
#
# Copyright 2021 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0
- name: Apply udev rule changes
  become: True
  command: udevadm trigger

- name: Reload NetworkManager configuration
  become: True
  service:
    name: NetworkManager.service
    state: reloaded
