---
# Ansible inventory for regular remote hosts
#
# Reference:
# - How to build your inventory — Ansible Documentation
#   https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
#
# Copyright 2021 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0

all:
  # 主機定義
  hosts:
    remotehost:
      ansible_host: 1.2.3.4
      ansible_port: 2222
      ansible_user: username
      ansible_password: userpass
      ansible_become_password: sudopass
