---
# Ansible inventory for regular remote hosts
#
# Reference:
# - How to build your inventory — Ansible Documentation
#   https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
#
# Copyright 2021 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0+

all:
  # 主機定義
  hosts:
    vagrant:
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_user: vagrant
      ansible_password: vagrant
      ansible_become_password: vagrant
      ansible_ssh_private_key: /home/brlin/文件/自由知識創作平台/作業系統 Operating Systems/Ubuntu/Ubuntu Desktop in Vagrant/.vagrant/machines/default/virtualbox/private_key
