# Playbook for applying customizations to managed nodess
#
# Copyright 2020 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0
- name: Apply OS customizations
  hosts: all
  roles:
    - name: '{{ playbook_dir }}/..'
