# Playbook for applying customizations to managed nodess
#
# Copyright 2020 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0
- name: Apply OS customizations
  hosts: all
  roles:
    - role: brlin.brlin_os_customizations
  environment: {}
    # Set these environment variables if you need to access the
    # internet via an HTTP/HTTPS proxy service
    #http_proxy: http://192.168.49.1:8228
    #https_proxy: http://192.168.49.1:8228
