# Copyright 2025 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0+
- name: Configure kernel parameters
  hosts: all
  become: yes
  tasks:
    - name: Import corresponding task list from the brlin_os_customizations role
      ansible.builtin.import_role:
        name: brlin.brlin_os_customizations
        tasks_from: configure-kernel-parameters.yml
