---
# Copyright 2022 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0
- name: Ensure control node is controllable
  hosts: all
  gather_facts: false
  tasks:
    - name: Attempt an Ansible connection to the managed node
      ping:
